services:
  app:
    build: ./app
    restart: always
    container_name: flask_app
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flaskdb
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=flaskdb
    volumes:
      - mysql_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mysql_data: